ALTER TABLE IF EXISTS balance
    ALTER COLUMN balance_datetime TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE IF EXISTS transfer_group
    ALTER COLUMN registration_date TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN effective_date TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS interest_rate
    ALTER COLUMN interest_rate_datetime TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE IF EXISTS debt
    ALTER COLUMN debit_datetime TYPE TIMESTAMP WITHOUT TIME ZONE;